version: "3"
services:
  backend:
    container_name: backend
    build: 
      context: ./backend
    volumes:
      - ./backend:/usr/app
      - /usr/app/node_modules
    environment:  
      - APP_PORT=80
    ports: ['80:80']
  frontend:
    container_name: frontend
    build:
      context: ./frontend
    volumes:
      - ./frontend:/app
      - /app/node_modules
    ports:
      - '8000:8000'
    environment:  
      - BACKEND_URL=http://localhost/api